#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# ruff: noqa

"""Scan every recipes/**/recipe.yaml envelope -> catalog.json + MATRIX.md.

MATRIX.md = a scenario-faceted coverage grid (glance) + a unified flat table (deep dive),
both generated from catalog.json. A new scenario just adds one grid panel + table rows — no
reshape (see RECIPE_CONSOLIDATION_NOTES.md C1). Do not hand-edit the outputs.

Usage:
  build_catalog.py [<k8s-root>]            regenerate catalog.json + inject the README matrix (writes)
  build_catalog.py --check [<k8s-root>]    CI drift guard: compare generated bytes to the committed
                                           files and exit 1 on drift WITHOUT writing (safe in a shared
                                           worktree; never mutates tracked files).
"""

import json
import re
import statistics
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("requires: pip install pyyaml")

sys.path.insert(0, str(Path(__file__).resolve().parent))
import recipe_hash as _rh  # full-recipe fingerprint (recipe semantics + rendered manifests)
import benchmark_id as _bid  # stable benchmark identity (image/extra_args-invariant)

# Maturity ladder (low → high). Colors form an INTUITIVE progression (empty → in-progress → working →
# approved → gold standard); each is visually distinct. The top two require HUMAN sign-off (★).
STATUS_ORDER = ["planned", "wip", "runs", "performant", "exemplar"]
BADGE = {
    "planned": "⚪",
    "wip": "🟡",
    "runs": "🟢",
    "performant": "✅",
    "exemplar": "🏆",
}
HUMAN = {"performant", "exemplar"}  # human-approved gates
MEANING = {
    "planned": "declared; nothing deployed yet",
    "wip": "up but NOT producing a completed sweep yet — deploying, smoke, erroring, capacity-blocked, first sweep in flight",
    "runs": "≥1 completed sweep produced numbers (unvetted; imperfect is fine). A factual bar — data exists",
    "performant": "human-approved — a person reviewed the results and confirmed they're real + good",
    "exemplar": "human-approved + a committed exemplar reference bar (the cross-cluster baseline)",
}
TUNING = "⚙"  # computed marker: has numbers, but the recipe moved since (RESULTS' recipe_hash != current)
# back-compat: old status names map onto the new ladder so a not-yet-migrated cell still renders.
ALIAS = {"deployable": "wip", "validated": "wip", "perf-data": "exemplar"}
_HASH_RE = re.compile(r"recipe_hash[^0-9a-fx]{0,24}([0-9a-f]{64})", re.I)
# fallback regexes for cells that predate runs.jsonl
_WALL_H_RE = re.compile(r"^\|\s*wall_h\s*\|\s*([\d.]+h)\s*\|", re.M)
_GPU_H_RE = re.compile(r"^\|\s*gpu_h\s*\|\s*([\d.]+ GPU[^\|]*)\|", re.M)


def norm(s):
    return ALIAS.get(s, s)


def rank(s):
    return STATUS_ORDER.index(norm(s)) if norm(s) in STATUS_ORDER else -1


def badge(s):
    return BADGE.get(norm(s), BADGE["planned"])


def tuning_flag(cell_dir, current_hash) -> bool:
    """True if RESULTS.md cites a recipe_hash that no longer matches — numbers exist but predate the
    current recipe (a cell that 'runs' AND is still being adjusted). Sticky: status stays, marker shows.
    """
    rp = cell_dir / "RESULTS.md"
    if not rp.exists():
        return False
    m = _HASH_RE.search(rp.read_text())
    return bool(m and m.group(1) != current_hash)


def load_timing(cell_dir) -> tuple[str, str]:
    """Return (wall_h, gpu_h) strings: median from runs.jsonl if present, else latest from RESULTS.md."""
    jl = cell_dir / "runs.jsonl"
    if jl.exists():
        runs = []
        for line in jl.read_text().splitlines():
            line = line.strip()
            if line:
                try:
                    runs.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
        wall_secs = [r["wall_seconds"] for r in runs if r.get("wall_seconds") is not None]
        gpu_hs = [
            r["wall_seconds"] * r["gpu_count"] / 3600
            for r in runs
            if r.get("wall_seconds") is not None and r.get("gpu_count") is not None
        ]
        if wall_secs:
            wh = round(statistics.median(wall_secs) / 3600, 1)
            wall_str = f"{wh}h"
            gpu_str = f"{round(statistics.median(gpu_hs), 1)} GPU·h" if gpu_hs else ""
            return wall_str, gpu_str
    # fallback: read latest values from RESULTS.md provenance table
    rp = cell_dir / "RESULTS.md"
    if not rp.exists():
        return "", ""
    text = rp.read_text()
    wm = _WALL_H_RE.search(text)
    gm = _GPU_H_RE.search(text)
    return (wm.group(1).strip() if wm else ""), (gm.group(1).strip() if gm else "")


def benchmark_id_collisions(rows: list[dict]) -> dict[str, list[dict]]:
    """Return IDs shared by distinct recipe definitions.

    `benchmark_id` deliberately ignores image and tuning changes to compare repeated runs of ONE cell over
    time. It must not collapse two separate recipe directories with different recipe_hash content: that is an
    ambiguous catalog row, not a valid comparison group.
    """
    by_id: dict[str, list[dict]] = {}
    for row in rows:
        by_id.setdefault(row["benchmark_id"], []).append(row)
    return {
        benchmark_id: entries
        for benchmark_id, entries in by_id.items()
        if len({entry["recipe_hash"] for entry in entries}) > 1
    }


def print_benchmark_id_collisions(collisions: dict[str, list[dict]]) -> None:
    for benchmark_id in sorted(collisions):
        print(f"BENCHMARK ID COLLISION {benchmark_id}: same identity has different recipe content")
        for row in sorted(collisions[benchmark_id], key=lambda row: row["_path"]):
            print(f"  {row['_path']}  recipe_hash={row['recipe_hash']}")


def main() -> int:
    args = [a for a in sys.argv[1:] if a != "--check"]
    check = "--check" in sys.argv[1:]
    root = Path(args[0]) if args else Path(__file__).resolve().parent.parent
    rows = []
    for rp in sorted((root / "recipes").glob("**/recipe.yaml")):
        env = (yaml.safe_load(rp.read_text()) or {}).get("envelope") or {}
        env["_path"] = str(rp.parent.relative_to(root))
        env["recipe_hash"] = _rh.recipe_hash(rp.parent)  # drift guard: any benchmark change flips this
        env["benchmark_id"] = _bid.benchmark_id(rp.parent)  # stable across image/flag rolls — group-by to compare
        env["_tuning"] = tuning_flag(rp.parent, env["recipe_hash"])  # numbers exist but recipe moved since
        env["_wall_h"], env["_gpu_h"] = load_timing(rp.parent)
        rows.append(env)

    collisions = benchmark_id_collisions(rows)
    if collisions:
        print_benchmark_id_collisions(collisions)
        print("matrix-check: FAIL — benchmark_id must not merge different recipe content")
        return 1

    catalog_content = json.dumps(rows, indent=2, ensure_ascii=False) + "\n"

    # --- build the matrix block (injected into README.md between markers) ---
    # Do not publish the internal recipe maturity state in the customer-facing matrix.
    block = [
        f"_Auto-generated by `scripts/build_catalog.py` — do not hand-edit between the markers._",
        "",
        f"**{len(rows)} recipes**",
        "",
    ]

    # faceted coverage grid, one panel per scenario
    block += [
        "### Coverage",
        "",
        "_✓ marks a covered model·GPU × engine·serving combo (`×N` = N cells there). "
        "Engine column: `engine` when no orchestration framework, "
        "`engine+framework` (e.g. `sglang+dynamo`) when one is used. Empty = not covered yet._",
        "",
    ]
    # facet by (scenario · goal) — the goal refines the scenario (WHAT the benchmark measures)
    facets = sorted({(r.get("scenario", "?"), r.get("goal") or "") for r in rows})

    def engine_key(r):
        """engine, or engine+framework when a non-trivial framework is present (e.g. sglang+dynamo)."""
        eng = r.get("engine", "?")
        fw = r.get("framework", "none") or "none"
        return f"{eng}+{fw}" if fw not in ("none", "", None) else eng

    for sc, goal in facets:
        srows = [r for r in rows if r.get("scenario") == sc and (r.get("goal") or "") == goal]
        dists = sorted({r.get("distribution", "?") for r in srows})
        title = f"{sc} · {goal}" if goal else sc
        block += [f"**{title}** — {', '.join(dists)}", ""]
        cols = sorted({f"{engine_key(r)}-{r.get('serving_mode','?')}" for r in srows})
        recs = sorted({f"{r.get('model','?')} · {r.get('gpu_type','?')}" for r in srows})
        block.append("| model · gpu | " + " | ".join(cols) + " |")
        block.append("|" + "---|" * (len(cols) + 1))
        for rec in recs:
            cells = []
            for col in cols:
                match = [
                    r
                    for r in srows
                    if f"{r.get('model','?')} · {r.get('gpu_type','?')}" == rec
                    and f"{engine_key(r)}-{r.get('serving_mode','?')}" == col
                ]
                if not match:
                    cells.append("")
                else:
                    cells.append(f"✓ ×{len(match)}" if len(match) > 1 else "✓")
            block.append(f"| {rec} | " + " | ".join(cells) + " |")
        block.append("")

    # unified flat table (recipe name -> its dir; results -> RESULTS.md)
    block += [
        "### Recipes",
        "",
        "_Two identities per row. **`benchmark_id`** = the stable identity of *what is measured* "
        "(model · hardware · deployment shape · workload · SLA); it stays constant across image rolls and "
        "`extra_args` tuning, so **group by it to compare results over time**. **`recipe_hash`** "
        "(`recipe_hash.py`) = the *exact recipe* — it additionally covers the image digest, every "
        "`extra_args` flag, and the rendered manifests, so it moves on any of those; **tag a run with it to "
        "prove the byte-identical setup**. `wall h (p50)` / `GPU·h (p50)` = median over all published runs "
        "logged in `runs.jsonl` (blank = not yet run; single run = that run's value)._",
        "",
        "| recipe | model | gpu | arch | agent | engine | serving | scenario | goal | distribution | mode | launcher | benchmark_id | recipe_hash | wall h (p50) | GPU·h (p50) | results |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in sorted(
        rows,
        key=lambda r: (
            r.get("scenario", ""),
            r.get("distribution", ""),
            r.get("model", ""),
            r.get("gpu_type", ""),
        ),
    ):
        link = r.get("results_link") or ""
        if link.startswith("./"):
            link = link[2:]
        # DATA-GATE the RESULTS link: new-cell.sh seeds `results_link: ./RESULTS.md` on EVERY cell, so an
        # ungated link points at a placeholder RESULTS.md even for empty/WIP cells (misleading). Only emit
        # the link once the cell actually HAS data — i.e. its status has reached `runs` ("≥1 completed sweep
        # produced numbers") or higher on the maturity ladder. rank() applies norm() (alias-aware).
        has_data = rank(r.get("status", "planned")) >= STATUS_ORDER.index("runs")
        res = f"[RESULTS]({r['_path']}/{link})" if (link and has_data) else ""
        name = f"[{r.get('name','')}]({r['_path']}/)"
        _ag = r.get("agent") or {}
        agent_col = f"{_ag.get('placement','')}·{_ag.get('arch','')}" if _ag else ""
        block.append(
            "| "
            + " | ".join(
                [
                    name,
                    r.get("model", ""),
                    r.get("gpu_type", ""),
                    r.get("arch", ""),
                    agent_col,
                    engine_key(r),
                    r.get("serving_mode", ""),
                    r.get("scenario", ""),
                    r.get("goal", "") or "",
                    r.get("distribution", ""),
                    r.get("mode", ""),
                    r.get("launcher", ""),
                    f"`{r.get('benchmark_id','')[:12]}`",
                    f"`{r.get('recipe_hash','')[:12]}`",
                    r.get("_wall_h", ""),
                    r.get("_gpu_h", ""),
                    res,
                ]
            )
            + " |"
        )

    # inject between the README markers (README is the human/agent entry point)
    readme = root / "README.md"
    catalog = root / "catalog.json"
    START, END = "<!-- MATRIX:START -->", "<!-- MATRIX:END -->"
    text = readme.read_text()
    if START not in text or END not in text:
        print("WARN: README.md has no <!-- MATRIX:START/END --> markers; matrix not injected")
        return 0
    pre, post = text.split(START)[0], text.split(END)[1]
    readme_content = f"{pre}{START}\n" + "\n".join(block) + f"\n{END}{post}"

    if check:
        # Read-only drift guard: compare generated bytes to committed; never write.
        drift = [
            p.name
            for p, want in ((catalog, catalog_content), (readme, readme_content))
            if (p.read_text() if p.exists() else None) != want
        ]
        if drift:
            print("MATRIX DRIFT — run 'make matrix' and commit: " + ", ".join(drift))
            return 1
        print("matrix-check OK (catalog.json + README matrix up to date)")
        return 0

    catalog.write_text(catalog_content)
    readme.write_text(readme_content)
    print(
        f"catalog.json written + matrix injected into README.md ({len(rows)} recipes, {len(facets)} scenario·goal facet(s))"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
