#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# ruff: noqa

"""reproduce.py — the SINGLE generator of every recipe page's "How to reproduce" block.

A recipe page must answer one question in one screen: *what three commands recreate this cell?*

    1. scripts/llmb-k8s init                      # pick your cluster → writes a profile
    2. scripts/llmb-k8s install <profile> --recipes <slug>
    3. scripts/llmb-k8s run <cell> <profile> --teardown --fetch

Everything else (render.sh, deploy.sh, stage-*.sh, sweep.sh, fetch_results.sh, `kubectl scale`, manual PVC
creation, hand-run aggregate/exemplar scripts) is a PRIMITIVE that the three verbs already drive. Those steps
kept getting copy/pasted into per-cell READMEs, went stale, and buried the happy path — so they are BANNED
from cell pages and the ban is CI-enforced (`--check`). The real escape hatches live in docs/CLI.md and
TROUBLESHOOTING.md, not on the recipe page.

GROUPS. Some cells only make sense as a family (e.g. a `-c16/-c32/-c64` concurrency ladder is
one example). A group is derived, not declared: cells must share the benchmark envelope, hardware and
architecture, launcher/mode, serving mode + stack + runtime image family, endpoint type, and nominal workload
shape. Only then are they the SAME runnable family at different points. This deliberately prevents an
aggregate cell, a disaggregated cell, a different runtime implementation, or a different ISL/OSL workload
from leaking into one install/run command.

Cross-hardware siblings (B200 ↔ GB300) deliberately do NOT form a group: you cannot run them on one cluster,
and `compare` is the verb for that axis. Image *repository* is part of the key, while tag/digest is not, so
an image roll stays in the same logical family but NVIDIA Dynamo and upstream SGLang do not collapse together.
A richer declared `envelope.group` block is not currently supported (no schema field, cell, or runtime
implementation), so this conservative derived key is the fail-safe.

A cell whose README carries a `SUPERSEDED` banner is excluded from its group's member list (you must not be
told to run it), but still gets the group block — that is exactly how it points you at its replacements. A
retired cell with exactly ONE replacement still gets that block (it just renders as the replacement's own
three steps): the "a singleton is not a group" rule suppresses a live cell's optional extra section, never a
retired cell's only content.

Usage:
  reproduce.py                 # --check every cell (CI drift + banned-step lint); exit 1 on any problem
  reproduce.py --write         # regenerate the block in every cell README.md between the markers
  reproduce.py --write <cell>  # just one cell
  reproduce.py --print <cell>  # print the block, write nothing

The block is injected between `<!-- REPRODUCE:START -->` / `<!-- REPRODUCE:END -->`; a README without the
markers gets them appended once (so an existing page is never clobbered above/below the region).
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("reproduce.py: requires pyyaml (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent

START = "<!-- REPRODUCE:START -->"
END = "<!-- REPRODUCE:END -->"
GENERATED_NOTE = "<!-- generated by scripts/reproduce.py — edit that, not this block (`make reproduce`) -->"

# Primitives that the three verbs already drive. Seeing one on a recipe page means the page is telling a
# copy/paste user to do by hand something `install`/`run` does for them — the exact rot this file exists to
# stop. Each entry is (substring, why-it-is-banned/what-replaces-it).
BANNED: list[tuple[str, str]] = [
    ("kubectl ", "`install` and `run` do every cluster mutation — no hand-kubectl on a recipe page"),
    ("scripts/render.sh", "`run` renders; the committed rendered/ is CI-drift-checked (`make render-check`)"),
    ("scripts/deploy.sh", "`run` deploys and waits Ready"),
    ("scripts/stage-dataset.sh", "`run` stages the dataset"),
    ("scripts/sweep.sh", "`run` sweeps"),
    ("scripts/fetch_results.sh", "`run --fetch` fetches"),
    ("scripts/submit.sh", "`run` is the front door; `llmb-k8s submit` is documented in docs/CLI.md"),
    ("analysis/llm-perf/aggregate_metrics.py", "`llmb-k8s publish` aggregates — never hand-aggregate numbers"),
    ("analysis/llm-perf/exemplar_check.py", "`llmb-k8s publish` checks against the exemplar"),
    ("analysis/llm-perf/sla_compare_dashboard.py", "`llmb-k8s publish` renders the charts into RESULTS.md"),
    ("scripts/recipe_hash.py", "`publish` stamps recipe_hash; `make provenance-check` guards it"),
    ("cp cluster-profiles/", "`llmb-k8s init` writes the profile — no template copy/edit"),
]

# `install --recipes` matches on the catalog name; `run` takes the cell PATH.
RUN_FLAGS = "--teardown --fetch"


# ── pure model ──────────────────────────────────────────────────────────────────────────────────────


def recipe(cell: Path) -> dict:
    """The parsed recipe document. PURE."""
    return yaml.safe_load((cell / "recipe.yaml").read_text()) or {}


def envelope(cell: Path) -> dict:
    return recipe(cell).get("envelope") or {}


def cell_slug(cell: Path) -> str:
    """What `llmb-k8s install --recipes` matches on: the envelope name (the catalog 'name', unique), falling
    back to the directory basename. PURE."""
    return (envelope(cell).get("name") or "").strip() or cell.name


def cell_rel(cell: Path, root: Path = ROOT) -> str:
    try:
        return str(cell.resolve().relative_to(root.resolve()))
    except (ValueError, OSError):
        return str(cell)


def is_superseded(cell: Path) -> bool:
    """A cell retired in favour of replacements — its README carries the committed `SUPERSEDED` banner. Such a
    cell must never appear in a group's 'run these' list. PURE (reads only the committed README)."""
    r = cell / "README.md"
    if not r.is_file():
        return False
    head = r.read_text().split(START)[0]
    return "SUPERSEDED" in head


def _image_family(ref: object) -> str:
    """Stable runtime repository from an OCI ref, excluding roll-specific tag/digest.

    `registry:port/repo:tag@sha256:...` becomes `registry:port/repo`. A digest-only or missing ref remains
    empty; those cells are still separated by their other serving identity. PURE.
    """
    value = str(ref or "").strip()
    if not value:
        return ""
    value = value.split("@", 1)[0]
    slash = value.rfind("/")
    colon = value.rfind(":")
    return value[:colon] if colon > slash else value


def _workload_shape(bench: dict) -> tuple:
    """The declared synthetic workload, using nominal lengths when available.

    Mean/stddev are intentionally not family axes: `nominal_isl`/`nominal_osl` are the user-facing
    workload identity, while the sampled mean/stddev implement its range ratio. Non-synthetic scenarios
    return an empty shape and remain distinguished by envelope.distribution/mode. PURE.
    """
    synthetic = bench.get("synthetic") or {}
    if not synthetic:
        return (None, None)
    return (
        synthetic.get("nominal_isl", synthetic.get("isl")),
        synthetic.get("nominal_osl", synthetic.get("osl")),
    )


def group_key(cell: Path) -> tuple:
    """Conservative runnable-family identity: same workload + deployment lineage, different point. PURE."""
    doc = recipe(cell)
    e = doc.get("envelope") or {}
    serving = doc.get("serving") or {}
    bench = doc.get("bench") or {}
    provenance = e.get("provenance") or {}
    image_ref = provenance.get("image_ref") or serving.get("image")
    return (
        e.get("scenario"),
        e.get("goal"),
        e.get("distribution"),
        e.get("model"),
        e.get("gpu_type"),
        e.get("arch"),
        e.get("engine"),
        e.get("serving_mode"),
        e.get("framework"),
        e.get("mode"),
        e.get("launcher"),
        serving.get("stack"),
        _image_family(image_ref),
        bench.get("endpoint_type"),
        _workload_shape(bench),
    )


def all_cells(root: Path = ROOT) -> list[Path]:
    return sorted({p.parent for p in (root / "recipes").glob("**/recipe.yaml")})


def live_siblings(cell: Path, root: Path = ROOT) -> list[Path]:
    """Every LIVE (non-superseded) cell sharing this cell's group key, in path order. PURE."""
    key = group_key(cell)
    if not all(key[:2]):  # no scenario/goal → not classifiable
        return []
    return [c for c in all_cells(root) if group_key(c) == key and not is_superseded(c)]


def group_members(cell: Path, root: Path = ROOT) -> list[Path]:
    """What this cell's block should name.

    LIVE cell → its family, and only when the family really is one: a singleton must not grow a fabricated
    'run the whole group' section, so fewer than two live members returns [].

    SUPERSEDED cell → its REPLACEMENTS, and ONE replacement is still the whole answer. (The 'a singleton is
    not a group' rule is about a live cell's *optional extra* affordance; for a retired cell the block is the
    only content on the page — suppressing it at N=1 would drop the page back to three steps that run the
    very cell the banner says not to run. That regression is what `-c16/-c32/-c64 → -1mctx` would have hit,
    since it retires three cells in favour of one.) PURE."""
    fam = live_siblings(cell, root)
    if is_superseded(cell):
        return fam  # ≥1 replacement is enough; 0 → no block
    return fam if len(fam) >= 2 else []


# ── rendering ───────────────────────────────────────────────────────────────────────────────────────


def three_steps(cell: Path, root: Path = ROOT) -> list[str]:
    """The canonical three commands for THIS cell. PURE."""
    return [
        "```bash",
        "# 1 · pick your cluster → writes cluster-profiles/<profile>.env  (one-time, per cluster)",
        "scripts/llmb-k8s init",
        "",
        "# 2 · install THIS recipe: namespace + secrets + model-cache PVC + weights  (safe to re-run)",
        f"scripts/llmb-k8s install <profile> --recipes {cell_slug(cell)}",
        "",
        "# 3 · run it: preflight → serve → sweep → results (GPUs freed on the way out)",
        f"scripts/llmb-k8s run {cell_rel(cell, root)} <profile> {RUN_FLAGS}",
        "```",
    ]


def group_block(cell: Path, root: Path = ROOT) -> list[str]:
    """The 'run the whole group' section, or [] when this cell is a singleton. PURE."""
    fam = group_members(cell, root)
    if not fam:
        return []
    e = envelope(cell)
    slugs = ",".join(cell_slug(c) for c in fam)
    paths = " ".join(cell_rel(c, root) for c in fam)
    if is_superseded(cell) and len(fam) == 1:
        # ONE replacement: a for-loop over a single path and a one-cell `compare` are theatre. The honest
        # answer is the replacement's own three steps.
        return [
            "",
            "### Reproduce the replacement cell",
            "",
            (
                f"This cell is retired; [`{fam[0].name}`](../{fam[0].name}) replaces it — same "
                f"`{e.get('scenario')}` · `{e.get('goal')}` · `{e.get('distribution')}` benchmark on the "
                f"same `{e.get('gpu_type')}` hardware. Its three steps:"
            ),
            "",
        ] + three_steps(fam[0], root)
    if is_superseded(cell):
        lead = (
            f"This cell is retired; its {len(fam)} replacements are the thing to reproduce — same "
            f"`{e.get('scenario')}` · `{e.get('goal')}` · `{e.get('distribution')}` benchmark on the "
            f"same `{e.get('gpu_type')}` hardware, at different points."
        )
        head = f"### Reproduce the {len(fam)} replacement cells"
    else:
        lead = (
            f"This cell is one of a family — same `{e.get('scenario')}` · `{e.get('goal')}` · "
            f"`{e.get('distribution')}` benchmark on the same `{e.get('gpu_type')}` hardware, at different "
            "points. Steps 1–3 above do one point; these do the family. Same three verbs."
        )
        head = f"### …or run the whole group ({len(fam)} cells)"
    out = [
        "",
        head,
        "",
        lead,
        "",
        "```bash",
        "# 1 · same one-time cluster profile" if is_superseded(cell) else None,
        "scripts/llmb-k8s init" if is_superseded(cell) else None,
        "" if is_superseded(cell) else None,
        "# 2 · install every member at once (one model cache, shared)",
        f"scripts/llmb-k8s install <profile> --recipes {slugs}",
        "",
        "# 3 · run them ONE AT A TIME — a benchmark never shares a node (whole-node exclusivity)",
        f"for CELL in {paths}; do",
        f"  scripts/llmb-k8s run $CELL <profile> {RUN_FLAGS}",
        "done",
        "",
        "# 4 · read the family as one frontier, once the members are published",
        f"scripts/llmb-k8s compare {paths}",
        "```",
    ]
    return [ln for ln in out if ln is not None]


def reproduce_md(cell: Path, root: Path = ROOT) -> str:
    """The full generated region (markers included). PURE + deterministic."""
    retired = is_superseded(cell) and group_members(cell, root)
    out = [START, GENERATED_NOTE, "", "## How to reproduce", ""]
    if retired:
        # A retired cell must NOT hand you a command that runs it — the whole page would contradict its own
        # banner. It gets the replacements' group block and nothing else.
        out += [
            "**Not this cell** — it is superseded (see the banner above). Reproduce its replacements "
            "instead, from `inference/k8s_recipes/`:"
        ]
    else:
        out += [
            "Three steps, run from `inference/k8s_recipes/`. Nothing else is needed — "
            "`install` provisions the cluster side and `run` drives the whole lifecycle.",
            "",
        ]
        out += three_steps(cell, root)
    out += group_block(cell, root)
    up = "../" * len(cell_rel(cell, root).split("/"))  # cell dir → collection root
    out += [
        "",
        "Numbers land in [`RESULTS.md`](RESULTS.md) (100% code-generated by `llmb-k8s publish`). "
        "Stuck, or need the underlying primitives? "
        f"[`docs/CLI.md`]({up}docs/CLI.md) · [`TROUBLESHOOTING.md`]({up}TROUBLESHOOTING.md)",
        END,
    ]
    return "\n".join(out)


def inject(text: str, block: str) -> str:
    """Replace the markered region, appending it once if the markers are absent. PURE."""
    if START in text and END in text:
        pre = text.split(START)[0]
        post = text.split(END, 1)[1]
        return pre + block + post
    return text.rstrip() + "\n\n" + block + "\n"


# ── lint ────────────────────────────────────────────────────────────────────────────────────────────


def banned_hits(text: str) -> list[str]:
    """Complicated-step regressions anywhere on the page (inside OR outside the generated region). PURE."""
    hits = []
    for needle, why in BANNED:
        if needle in text:
            hits.append(f"'{needle}' — {why}")
    return hits


def check_cell(cell: Path, root: Path = ROOT) -> list[str]:
    rel = cell_rel(cell, root)
    readme = cell / "README.md"
    if not readme.is_file():
        return [f"{rel}/README.md: missing"]
    text = readme.read_text()
    problems = []
    want = reproduce_md(cell, root)
    if START not in text or END not in text:
        problems.append(f"{rel}/README.md: no {START} … {END} region (run `make reproduce`)")
    else:
        got = START + text.split(START, 1)[1].split(END, 1)[0] + END
        if got != want:
            problems.append(f"{rel}/README.md: reproduce block is STALE (run `make reproduce`)")
    for h in banned_hits(text):
        problems.append(f"{rel}/README.md: banned manual step {h}")
    return problems


def main(argv: list[str]) -> int:
    write = "--write" in argv
    do_print = "--print" in argv
    pos = [a for a in argv if not a.startswith("-")]
    cells = [Path(p) for p in pos] if pos else all_cells()
    if not cells:
        print("reproduce: no cells")
        return 0

    if do_print:
        for c in cells:
            print(reproduce_md(c))
        return 0

    if write:
        changed = 0
        for c in cells:
            readme = c / "README.md"
            old = readme.read_text() if readme.is_file() else f"# {c.name}\n"
            new = inject(old, reproduce_md(c))
            if new != old:
                readme.write_text(new)
                changed += 1
                print(f"  updated {cell_rel(c)}/README.md")
        print(f"reproduce: {changed}/{len(cells)} README(s) updated")
        return 0

    problems = []
    for c in cells:
        problems += check_cell(c)
    for p in problems:
        print(f"FAIL {p}")
    if problems:
        print(f"reproduce-check: {len(problems)} problem(s) — fix, or run `make reproduce`")
        return 1
    print(f"reproduce-check OK ({len(cells)} cells: three-step block current, no banned manual steps)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
